In [14]:
import time
start = time.perf_counter() 
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[1, 0, 0],
     [0, 1, 0]]

A_plus_B = [[A[i][j] + B[i][j]  
            for j in range(len(A[0]))] 
            for i in range(len(A))]

print(A_plus_B)
# 获取结束时间
end = time.perf_counter() 
# 计算运行时间
runTime = end - start
runTime_ms = runTime * 1000
# 输出运行时间
print("运行时间：", runTime, "秒")
print("运行时间：", runTime_ms, "毫秒")

[[2, 2, 3], [4, 6, 6]]
运行时间： 0.0002391000000443455 秒
运行时间： 0.2391000000443455 毫秒


In [15]:
import numpy as np

start = time.perf_counter() 
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[1, 0, 0],
     [0, 1, 0]]

print(np.array(A) + np.array(B))

print(np.add(A, B))
# 获取结束时间
end = time.perf_counter() 
# 计算运行时间
runTime = end - start
runTime_ms = runTime * 1000
# 输出运行时间
print("运行时间：", runTime, "秒")
print("运行时间：", runTime_ms, "毫秒")

[[2 2 3]
 [4 6 6]]
[[2 2 3]
 [4 6 6]]
运行时间： 0.0010132999999541425 秒
运行时间： 1.0132999999541425 毫秒
